# Generated by Django 3.0.6 on 2020-06-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.CharField(default='1998-01-01', max_length=100),
        ),
    ]
